# Site
repository: sproogen/resume-theme
favicon: images/favicon.ico

# Personal info
name: Ankit Sarraf
title: Senior Big Data Engineer
email: Let's connect on LinkedIn
# website: asarraf.github.io

darkmode: true

# Social links
# twitter_username: facespics
# github_username:  asarraf
# dribbble_username: jekyll
# facebook_username: jekyll
# flickr_username: jekyll
# instagram_username: chillwildlife
linkedin_username: ankitsarraf
# pinterest_username: jekyll
# youtube_username: globalmtb
# googleplus_username: +jekyll

# About Section
# about_title: About Me
about_profile_image: images/asarraf.jpg
about_content: | # this will include new lines to allow paragraphs
  Hi, my name is Ankit and I'm a Senior Big Data Engineer with [Palo Alto Networks](https://www.paloaltonetworks.com/).<br/>
  I am a proud Alumni of [University of Buffalo](http://www.buffalo.edu/) and [Nirma University](https://nirmauni.ac.in/)

  I am most skilled in: <mark>GCP</mark> and <mark>Dancing with Confidence</mark>

# Projects Section
# projects_title: Projects

# Experience Section
# experience_title: Experience

# Education Section
# educaton_title: Education

# More Section
# more_title: A Little More About Me
more_content: | # this will include new lines to allow paragraphs
  Alongside my interests in Big Data Engineering, I am curious about:
   - Economics
   - Product Designing
   - Cybersecurity

  And, I love, Running!

# Footer
footer_show_references: false

# Build settings
remote_theme: sproogen/resume-theme

sass:
  sass_dir: _sass
  style: compressed

plugins:
 - jekyll-seo-tag
